# Assignment 2: NumPy
Values from assignment: 

In [2]:
import numpy as np

# machine id, temp, vibration, pressure, energy use
data = np.array([
[101, 72.4, 2.1, 101.3, 12.5],
[102, 85.1, 5.8, 98.7, 15.2],
[103, 69.8, 1.9, 102.1, 11.8],
[104, 91.3, 7.2, 97.4, 18.1],
[105, 76.5, 3.0, 100.5, 13.7],
[106, -999, 4.1, 99.9, 14.8],
[107, 88.7, 6.5, 96.8, 17.3],
[108, 73.2, 2.4, 101.8, 12.9],
[109, 79.6, 3.8, 100.1, 14.2],
[110, 95.2, 8.1, 95.9, 20.4]
])

#### Task 1: **Inspect the batch**   
Report data.shape, data.ndim, data.size, and data.dtype. Explain
why Machine ID is stored as a floating-point value even though its values look like integers.

In [ ]:
print(f"Shape: {data.shape}")
print(f"Number of dimensions: {data.ndim}")
print(f"Number of elements: {data.size}")
print(f"Array data type: {data.dtype}")
print("The Machine ID must be stored as a floating-point value in order to be in the array, as arrays must have the same data type for every element.")

Shape: (10, 5)
Number of dimensions: 2
Number of elements: 50
Array data type: float64
The Machine ID must be stored as a floating-point value in order to be in the array, as arrays must have the same data type for every element.


#### Task 2: **Separate identifiers from measurements**  
Create a one-dimensional array named machine_ids
containing the first column. Create a two-dimensional array named measurements containing temperature, vibration, pressure, and energy usage. Confirm the shape of each result.

In [23]:
# all machine ids are stored in the first column
machine_ids = data[:,0].copy()                  
print(f"Machine IDs: {machine_ids}")
print(f"Machine IDs size: {machine_ids.size} \n")

# selects all columns after the machine ids
measurements = data[:, 1:].copy()
print(f"Measurements: \n {measurements}")
print(f"Measurements size: {measurements.size}")

Machine IDs: [101. 102. 103. 104. 105. 106. 107. 108. 109. 110.]
Machine IDs size: 10 

Measurements: 
 [[  72.4    2.1  101.3   12.5]
 [  85.1    5.8   98.7   15.2]
 [  69.8    1.9  102.1   11.8]
 [  91.3    7.2   97.4   18.1]
 [  76.5    3.   100.5   13.7]
 [-999.     4.1   99.9   14.8]
 [  88.7    6.5   96.8   17.3]
 [  73.2    2.4  101.8   12.9]
 [  79.6    3.8  100.1   14.2]
 [  95.2    8.1   95.9   20.4]]
Measurements size: 40


#### Task 3: **Validate the records**  
Create a Boolean mask that identifies every row containing -999 in its
measurement columns. Report the Machine ID associated with each invalid row.

In [71]:
# checks if any row (axis = 1) has a value = -99 (bool comparison)
mask_invalid = np.any(measurements == -999, axis=1) 
print(f"Boolean mask: \n{mask_invalid}\n")

# selects the missing id (col 0) of row with mask = true
invalid_ids = machine_ids[mask_invalid]
print(f"Invalid ids: {invalid_ids}")

Boolean mask: 
[False False False False False  True False False False False]

Invalid ids: [106.]


#### Task 4: **Filter the batch**  
Use the validation mask to create clean_ids and clean_measurements.
Both arrays must contain only valid records and must remain aligned row by row.


In [ ]:
# shows all rows (axis = 1) that do not include -999
mask_valid = np.all(measurements != -999, axis=1) 

# selects the values that are true from bool statement above
clean_ids = machine_ids[mask_valid]
clean_measurements = measurements[mask_valid]

print(f"Clean ID's: {clean_ids}\n")
print(f"Clean measurements:\n{clean_measurements}")

Clean ID's: [101. 102. 103. 104. 105. 107. 108. 109. 110.]

Clean measurements:
[[ 72.4   2.1 101.3  12.5]
 [ 85.1   5.8  98.7  15.2]
 [ 69.8   1.9 102.1  11.8]
 [ 91.3   7.2  97.4  18.1]
 [ 76.5   3.  100.5  13.7]
 [ 88.7   6.5  96.8  17.3]
 [ 73.2   2.4 101.8  12.9]
 [ 79.6   3.8 100.1  14.2]
 [ 95.2   8.1  95.9  20.4]]


#### Task 5: **Aggregate the clean data**  
For each measurement column, calculate its mean, minimum,
and maximum. The output must summarize temperature, vibration, pressure, and energy usage separately. Pay close attention to the axis argument.

In [ ]:
# calculate through measurement columns (axis = 0)
# creates arrays of values
means = clean_measurements.mean(axis = 0)
mins = clean_measurements.min(axis = 0)
maxs = clean_measurements.max(axis = 0)

# use indexing via column number to find values for each measurement
print("Aggregate values presented in order: (mean, max, min)")
print(f"Temperature: ({means[0]:.1f}, {mins[0]}, {maxs[0]})")
print(f"Vibration: ({means[1]:.1f}, {mins[1]}, {maxs[1]})")
print(f"Pressure: ({means[2]:.1f}, {mins[2]}, {maxs[2]})")
print(f"Energy usage: ({means[3]:.1f}, {mins[3]}, {maxs[3]})")

Aggregate values presented in order: (mean, max, min)
Temperature: (81.3, 69.8, 95.2)
Vibration: (4.5, 1.9, 8.1)
Pressure: (99.4, 95.9, 102.1)
Energy usage: (15.1, 11.8, 20.4)


#### Task 6: **Transform temperature**  
Convert the clean temperature values from Celsius to Fahrenheit.

In [73]:
# copy values of all temperatures in 1-D array
temps_c = clean_measurements[:,0].copy()

# use ufunc
temps_f = ((9/5) * temps_c) + 32
print(f"Temperatures in farenheit: {temps_f}")

Temperatures in farenheit: [162.32 185.18 157.64 196.34 169.7  191.66 163.76 175.28 203.36]


#### Task 7: **Apply a quality rule**  
Combine Boolean conditions to create an inspection mask, then report the corresponding Machine IDs.

In [90]:
# temperature > 85C, vibration > 6.0
# select just temperatures and vibrations
temps = clean_measurements[:,0]
vibes = clean_measurements[:,1]

# make mask with requirements
quality_mask = (temps > 85.0) | (vibes > 6.0)

# print out ids
quality_ids = clean_ids[quality_mask]
print(f"Machines that require inspection: {quality_ids}")

Machines that require inspection: [102. 104. 107. 110.]


#### Task 8: **Center the measurements**  
Calculate the mean of each clean measurement column and subtract those means from the clean data using broadcasting. Verify with NumPy that every column mean in the centered array is approximately zero.  Briefly explain why tiny nonzero values may appear.

In [85]:
# the array of measure means was calculated in Task 5
differences = clean_measurements - means

# Sums the differences in each column
difference_sums = differences.sum(axis=0)

print(f"Centered temperatures: {difference_sums[0]}")
print(f"Centered vibrations: {difference_sums[1]}")
print(f"Centered pressures: {difference_sums[2]}")
print(f"Centered energy usages: {difference_sums[3]}")

print("\nThe values are all approx 0. The minor variations from 0 come from the rounding of each calculated mean value.")


Centered temperatures: -5.684341886080802e-14
Centered vibrations: 4.440892098500626e-16
Centered pressures: 7.105427357601002e-14
Centered energy usages: 3.552713678800501e-15

The values are all approx 0. The minor variations from 0 come from the rounding of each calculated mean value.


#### Task 9. **Produce a quality summary.**  
Print a final report containing:
- number of raw records;
- number of clean records;
- number of rejected records; and
- number of machines flagged for inspection.

In [89]:
raw = len(data)
clean = len(clean_measurements)
rejected = len(invalid_ids)
flagged = len(quality_ids)

print(f"Number of raw records = {raw}")
print(f"Number of clean records = {clean}")
print(f"Number of rejected records = {rejected}")
print(f"Number of machines flagged for inspection = {flagged}")

print(f"Check:\n Raw = {raw} \n Clean + Rejected =", clean + rejected)


Number of raw records = 10
Number of clean records = 9
Number of rejected records = 1
Number of machines flagged for inspection = 4
Check:
 Raw = 10 
 Clean + Rejected = 10
